chore: add maintainers as codeowners to all files
hashgraph/full-stack-testing pull request #1013
Opened 2024-12-10 12:25 UTC by PavelSBorisov

**Description**:
Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Related issue(s)**:

Fixes #171 

**Notes for reviewer**:
N/A

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-13 14:48 UTC, andrewb1269hg requested changes

2024-12-13 14:48 UTC, andrewb1269hg commented on .github/CODEOWNERS
> +.releaserc                                      @hashgraph/release-engineering-managers @hashgraph/release-engineering
Add `@hashgraph/devops-ci` to the `.releaserc` file.

2024-12-13 14:48 UTC, andrewb1269hg commented on .github/CODEOWNERS
> +/.github/workflows/                             @hashgraph/release-engineering-managers @hashgraph/devops-ci @hashgraph/release-engineering
Confirm with @rbarkerSL but I think `release-engineering` should be removed from the `workflows` folder.

2024-12-13 18:19 UTC, rbarkerSL commented on .github/CODEOWNERS
> +/.github/workflows/                             @hashgraph/release-engineering-managers @hashgraph/devops-ci @hashgraph/release-engineering
Not on this one.

2024-12-13 18:20 UTC, rbarkerSL requested changes

2024-12-13 18:20 UTC, rbarkerSL commented on .github/CODEOWNERS
>  **/codecov.yml                                  @hashgraph/release-engineering @hashgraph/release-engineering-managers
```suggestion
**/codecov.yml                                  @hashgraph/release-engineering @hashgraph/release-engineering-managers @hashgraph/devops-ci @hashgraph/devops-ci-committers 
```

2024-12-16 13:36 UTC, andrewb1269hg approved these changes

2024-12-17 04:37 UTC, rbarkerSL approved these changes

2024-12-17 08:03 UTC, merged