Add first draft of Infrastructure API and related models
hashgraph/full-stack-testing pull request #407
Opened 2023-10-12 17:30 UTC by deepak-swirlds

## Description

This pull request changes the following:

- First Draft of the Infrastructure API
- Any supporting model classes

### Related Issues

- Closes #301

2023-10-17 03:59 UTC, leninmehedy commented
@deepak-swirlds I remember you wanted to close this PR and start creating smaller ones. Is that still the plan? If yes, please close this PR to avoid noise in our PR list.

2023-11-03 17:51 UTC, jeromy-cannon commented on fullstack-core/fullstack-alerting-core/build.gradle.kts
> +    implementation(project(mapOf("path" to ":fullstack-infrastructure-api")))
I don't see a problem, but normally we would want to include new dependencies in the same PR where they are consumed.  In this PR you are adding dependencies, but you aren't adding any code that requires them.

2023-11-03 17:51 UTC, jeromy-cannon commented on fullstack-core/fullstack-assertj-extensions/build.gradle.kts
> +    implementation(project(mapOf("path" to ":fullstack-base-api")))
I don't see a problem, but normally we would want to include new dependencies in the same PR where they are consumed.  In this PR you are adding dependencies, but you aren't adding any code that requires them.

2023-11-03 17:54 UTC, jeromy-cannon commented on fullstack-core/fullstack-configuration-api/src/main/java/com/hedera/fullstack/configuration/model/Node.java
> +public record Node(int RAM, int CPU, int nodeID, int nodeAccountID) {}
RAM and CPU need to be lowercase to adhere to code style, unless I'm misunderstanding and this is a constant.

2023-11-03 17:56 UTC, jeromy-cannon commented on fullstack-core/fullstack-configuration-api/src/main/java/com/hedera/fullstack/configuration/model/Topology.java
> +public record Topology(List<Node> nodes) {}
Where did we land on coming up with a different name other than Topology?

2023-11-03 18:04 UTC, jeromy-cannon commented on fullstack-core/fullstack-infrastructure-api/build.gradle.kts
>  }
I believe you can just write this as:
    implementation(project(":fullstack-configuration-api"))

same for the line above it.  I think the "mapOf("path" comes from IntelliJ solution to fix

2023-11-03 18:04 UTC, jeromy-cannon commented on fullstack-core/fullstack-infrastructure-core/build.gradle.kts
> +    implementation(project(mapOf("path" to ":fullstack-configuration-api")))
I believe you can remove the mapOf("path" part

2023-11-03 18:06 UTC, jeromy-cannon commented on fullstack-core/fullstack-resource-generator-api/build.gradle.kts
> +    implementation(project(mapOf("path" to ":fullstack-configuration-api")))
I believe you can remove the mapOf("path"

2023-11-03 18:18 UTC, deepak-swirlds commented on fullstack-core/fullstack-configuration-api/src/main/java/com/hedera/fullstack/configuration/model/Topology.java
> +public record Topology(List<Node> nodes) {}
This really is the topolgy its wrapper in a this we discussed called NetworkDeploymentConfiguration

2023-11-03 18:34 UTC, jeromy-cannon commented on fullstack-core/fullstack-alerting-core/build.gradle.kts
> +    implementation(project(mapOf("path" to ":fullstack-infrastructure-api")))
if you decide to keep this, did you want to remove the mapOf("path" instances in this file?

2023-11-03 18:34 UTC, jeromy-cannon commented on fullstack-core/fullstack-assertj-extensions/build.gradle.kts
> +    implementation(project(mapOf("path" to ":fullstack-base-api")))
if you decide to keep this, did you want to remove the mapOf("path" instances in this file?

2023-11-05 23:13 UTC, leninmehedy commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/jsonrpcrelay/EthBridge.java
> +public class EthBridge extends AbstractWorkload<EthBridge> {}
It was not very clear what `EthBridge` is. Probably a different or longer name would be better. Also needs a doc block.

2023-11-05 23:22 UTC, leninmehedy commented on fullstack-core/fullstack-resource-generator-api/src/main/java/com/hedera/fullstack/resource/generator/api/ResourceUtils.java
> +public interface ResourceUtils {
I suppose this class will evolve a bit more as we discover the needs. There could be utility package with separate responsibilities instead of a single utility class

2023-11-05 23:25 UTC, leninmehedy approved these changes
Thanks. Let's merge this first version and start focusing on polishing smaller parts one at a time. It is difficult to get it perfect in one go... This is already a too big PR.

2023-11-05 23:28 UTC, leninmehedy commented
@deepak-swirlds before merging, please ensure DCO check is passing

2023-11-06 13:35 UTC, jeromy-cannon approved these changes

2023-11-06 16:10 UTC, nathanklick requested changes

2023-11-07 02:28 UTC, nathanklick requested changes

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-configuration-api/src/main/java/com/hedera/fullstack/configuration/model/NetworkDeploymentConfiguration.java
> +    Topology topology;
Topology should be inlined and doesn't need to exist.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-configuration-api/src/main/java/com/hedera/fullstack/configuration/model/Node.java
> +public record Node(int ram, int cpu, int nodeID, int nodeAccountID) {}
Needs javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-configuration-api/src/main/java/com/hedera/fullstack/configuration/model/Topology.java
> +public record Topology(List<Node> nodes) {}
Remove this and inline in the `NetworkDeploymentConfiguration` class.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-configuration-api/src/main/java/module-info.java
> +    exports com.hedera.fullstack.configuration.model;
Rename the model package to something like `infrastructure`.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/Cluster.java
> + * A {@link Cluster}
```suggestion
 * A logical representation of a single Kubernetes control plane. 
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/Cluster.java
> +     * @return the {@link Workload} hosted on this {@link Cluster} of the given type
Needs a description and declared exceptions with documentation.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/Component.java
> +public interface Component extends Labeled {
Missing javadoc on both the class and all methods.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    String getId();
Missing javadoc and should be standardized to fluent style of accessor. We shouldn't mix and match Java Beans and Fluent accessors.

```suggestion
    String id();
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    String getName();
Missing javadoc and should be standardized to fluent style of accessor. We shouldn't mix and match Java Beans and Fluent accessors.

```suggestion
    String name();
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    NetworkDeploymentConfiguration getNetworkDeploymentConfiguration();
Missing javadoc and should be standardized to fluent style of accessor. We shouldn't mix and match Java Beans and Fluent accessors.

This should also be shortened as the method name is exceptionally long.

```suggestion
    NetworkDeploymentConfiguration configuration();
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    PlatformConfiguration.Builder getPlatformConfigurationBuilder();
Missing javadoc and should be standardized to fluent style of accessor. We shouldn't mix and match Java Beans and Fluent accessors.

Honestly this should be part of `NetworkDeploymentConfiguration` and not a separate getter here.

```suggestion
    PlatformConfiguration.Builder platformConfigBuilder();
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    List<Cluster> clusters();
Missing javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    List<Workload> workloads();
Missing javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    <T extends Workload> WorkloadReplica<T> workloadByIndex(Class<T> workloadType, int index);
Missing javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    <T extends Workload> List<WorkloadReplica<T>> workloadsByCluster(Class<T> workloadType, Cluster cluster);
Missing javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/NetworkDeployment.java
> +    Future<Boolean> installClusterSetupWorkloads() throws InstallationException;
Missing javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/Workload.java
> +     * @return the {@link WorkloadReplica}s that are part of this {@link Workload}
Add description to the javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/Workload.java
> +     * @return the {@link Cluster} on which this {@link Workload} is deployed
Add description to the javadoc.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/WorkloadReplica.java
> +    public int index() {
Needs javadoc and accessor should always come after the contructor declarations.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/WorkloadReplica.java
> +    public WorkloadReplica(List<Component> components, int index) {
Method arguments for concrete classes should be `final`. Needs javadoc. Needs docs for exceptions thrown and needs safety checks for `null`. 

```suggestion
    public WorkloadReplica(final List<Component> components, final int index) {
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/WorkloadReplica.java
> +    public List<Component> getComponents() {
```suggestion
    public List<Component> components() {
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/WorkloadReplica.java
> +    public <C extends Component> C getComponentByType(Class<C> componentType) {
Needs javadoc and exception docs.

```suggestion
    public <C extends Component> C componentByType(final Class<C> componentType) {
```

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/WorkloadReplica.java
> +                .get();
Is this behavior correct to only return the first component of the given type even if there are multiple matches? Should we permit multiple components of the same type within a single workload replica?

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/jsonrpcrelay/EthBridge.java
> +public class EthBridge extends AbstractWorkload<EthBridge> {}
These are implementation classes and should be moved to the implementation module.

2023-11-07 02:28 UTC, nathanklick commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/jsonrpcrelay/JSONRPCRelay.java
> +public class JSONRPCRelay extends AbstractWorkload<JSONRPCRelay> {}
These are implementation classes and should be moved to the implementation module. Needs Javadoc.

2023-11-17 10:55 UTC, deepak-swirlds commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/model/WorkloadReplica.java
> +                .get();
Opened issue:
https://github.com/hashgraph/full-stack-testing/issues/568

2023-12-11 00:14 UTC, leninmehedy commented
Closing it as discussed

2024-05-31 13:24 UTC, jeromy-cannon commented
@nathanklick , @leninmehedy 

going to close this PR, we can reopen or pull code from it as needed.

2024-05-31 13:24 UTC, closed without merging