bug: set fullstack-cluster-setup to default true for installing minio & prometheus-stack
hashgraph/full-stack-testing pull request #480
Opened 2023-11-02 14:29 UTC by jeromy-cannon

## Description

This pull request changes the following:

- set fullstack-cluster-setup to default true for installing minio & prometheus-stack

### Related Issues

- Closes #475

2023-11-02 14:38 UTC, nathanklick requested changes

2023-11-02 14:38 UTC, nathanklick commented on charts/fullstack-cluster-setup/values.yaml
> +    enabled: true
Let's not change the default. These are operators and should only be installed if not already available in the cluster. Installing multiple copies will cause operational issues within a cluster.

2023-11-02 14:48 UTC, jeromy-cannon commented on charts/fullstack-cluster-setup/values.yaml
> +    enabled: true
okay, well I guess https://github.com/hashgraph/full-stack-testing/issues/475 isn't needed.  Or, we just need to update fsnetman to set the values.  As, it sounds like @leninmehedy

2023-11-02 16:28 UTC, jeromy-cannon commented on charts/fullstack-cluster-setup/values.yaml
> +    enabled: true
fixed

2023-11-02 16:40 UTC, nathanklick commented on fullstack-network-manager/src/commands/cluster.mjs
> +    }
```suggestion
    prepareValuesArg(prometheusStackEnabled, minioEnabled) {
        return ` --set cloud.prometheusStack.enabled=${prometheusStackEnabled} --set cloud.minio.enabled=${minioEnabled}`
    }
```

2023-11-02 16:40 UTC, nathanklick commented on fullstack-network-manager/src/commands/cluster.mjs
> +            let valuesArg = this.prepareValuesArg(argv)
```suggestion
            let valuesArg = this.prepareValuesArg(argv.prometheusStack, argv.minio)
```

2023-11-02 17:59 UTC, nathanklick approved these changes

2023-11-02 18:01 UTC, merged

2023-11-03 17:27 UTC, swirlds-automation commented
:tada: This PR is included in version 0.12.0 :tada:

The release is available on:
- [GitHub release](https://github.com/hashgraph/full-stack-testing/releases/tag/v0.12.0)
- `npm package (@latest dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: