feat: allow user to create and update accounts with funds from treasury
hashgraph/full-stack-testing pull request #759
Opened 2024-02-14 20:50 UTC by jeromy-cannon

## Description

This pull request changes the following:

- allow user to create and update accounts with funds from treasury 

### Related Issues

- Closes #669

2024-02-14 21:57 UTC, jeromy-cannon commented
I should probably update the readme.  I can do it in a separate issue/PR, though.

2024-02-14 22:46 UTC, leninmehedy commented on solo/src/commands/account.mjs
> +    if (amount) {
We should ensure `amount` is a valid number (e.g. by trying to parse as float Number.parseFloat)

2024-02-14 22:48 UTC, leninmehedy commented on solo/src/commands/account.mjs
> +          self.ctx = ctx // useful for validation in e2e testing
Do we really need to store `ctx` in the class since semantically `ctx` is something that we pass to other methods.

2024-02-14 22:50 UTC, leninmehedy commented on solo/src/commands/flags.mjs
> +  name: 'stdout-private-key',
We shouldn't output private key in the console ever. Rather it should be stored in `cache/accounts/0.0.x/private-key.pem` and show user where to find the file.

2024-02-14 22:53 UTC, leninmehedy commented on solo/src/commands/account.mjs
> +          self.ctx = ctx // useful for validation in e2e testing
I can see you left a note saying it is useful in e2e testing, but I think we might be able to go around this.

2024-02-14 22:54 UTC, leninmehedy commented on solo/src/commands/account.mjs
> +    return true
It should return the `ctx.accountInfo` which would negate the requirement of `ctx` for e2e.

2024-02-14 22:57 UTC, leninmehedy requested changes
Thanks. Please review my comments.

2024-02-15 13:32 UTC, jeromy-cannon commented on solo/src/commands/account.mjs
> +    if (amount) {
done

2024-02-15 13:33 UTC, jeromy-cannon commented on solo/src/commands/account.mjs
> +          self.ctx = ctx // useful for validation in e2e testing
done

2024-02-15 13:34 UTC, jeromy-cannon commented on solo/src/commands/flags.mjs
> +  name: 'stdout-private-key',
I removed the stdout options.  FYI, these keys are never stored anywhere except within the Kubernetes cluster/namespace as secrets.  The user will need to retrieve them from the Kubernetes secrets if they ever need them.

2024-02-15 13:34 UTC, jeromy-cannon commented on solo/src/commands/account.mjs
> +    return true
done

2024-02-15 22:38 UTC, leninmehedy approved these changes

2024-02-16 11:18 UTC, merged

2024-02-23 15:49 UTC, swirlds-automation commented
:tada: This PR is included in version 0.22.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/full-stack-testing/releases/tag/v0.22.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: