feat: add extra container for sidecar uploader
hashgraph/full-stack-testing pull request #926
Opened 2024-07-17 21:09 UTC by JeffreyDallas

## Description

This pull request changes the following:

- Add another pod for hosting sidecar uploader

### Related Issues

- Closes #919

2024-07-17 23:52 UTC, leninmehedy commented on charts/fullstack-deployment/values.yaml
> +          prioritize: true
```suggestion
        signature:
          require: false
          prioritize: false
```
Based on Ivo's comment: https://swirldslabs.slack.com/archives/C06FWU24B7Y/p1720445868302879

2024-07-17 23:53 UTC, leninmehedy commented on charts/fullstack-deployment/templates/network-node-statefulset.yaml
> +            value: {{ $cloud.buckets.streamBucket | quote }}
```suggestion
          - name: BUCKET_PATH
            value: "recordstreams/record{{ $node.accountId }}/sidecar"
          - name: BUCKET_NAME
            value: {{ $cloud.buckets.streamBucket | quote }}
```
Based on Ivo's comment: https://swirldslabs.slack.com/archives/C06FWU24B7Y/p1720445868302879

2024-07-18 00:03 UTC, leninmehedy commented on charts/fullstack-deployment/values.yaml
> +          prioritize: true
I've checked the bucket and it does have a sidecar directory like `.../recordstreams/record0.0.10/sidecar` and it does not contain the signature file.

2024-07-18 09:17 UTC, Ivo-Yankov requested changes
Looks good. Can you also add one more change to `fullstack-deployment/values.yaml`:  Set this value `hedera.mirror.importer.parser.record.sidecar.enabled=true`. This will enable the importing of sidecar records to the mirror node.

2024-07-24 16:53 UTC, JeffreyDallas commented on charts/fullstack-deployment/templates/network-node-statefulset.yaml
> +            value: {{ $cloud.buckets.streamBucket | quote }}
Fixed

2024-07-24 16:53 UTC, JeffreyDallas commented on charts/fullstack-deployment/values.yaml
> +          prioritize: true
Fixed

2024-07-25 07:39 UTC, Ivo-Yankov approved these changes
LGTM

2024-07-26 01:52 UTC, merged

2024-08-01 00:34 UTC, swirlds-automation commented
:tada: This PR is included in version 0.29.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/full-stack-testing/releases/tag/v0.29.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: