chore: remove docker and charts directory
hashgraph/full-stack-testing pull request #988
Opened 2024-10-08 21:24 UTC by JeffreyDallas

## Description

This pull request changes the following:

- remove docker and charts directory
- update gradle build to remove dependency on helm charts

### Related Issues

- Closes #987

2024-10-09 12:32 UTC, jeromy-cannon commented on fullstack-core/fullstack-helm-client/build.gradle.kts
We still want to keep the fullstack-helm-client.  at least until we do a redesign based on changes in solo-operator.

2024-10-09 12:33 UTC, jeromy-cannon commented on fullstack-core/fullstack-infrastructure-api/src/main/java/com/hedera/fullstack/infrastructure/api/providers/K8sInfrastructureManager.java
we still want to keep this until we do a redesign with solo-operator in mind.

2024-10-09 12:33 UTC, jeromy-cannon commented on fullstack-examples/build.gradle.kts
keep

2024-10-09 12:34 UTC, jeromy-cannon commented on fullstack-gradle-plugin/src/main/kotlin/com/hedera/fullstack/gradle/plugin/FullstackPlugin.kt
keep the gradle plugin also

2024-10-09 12:35 UTC, jeromy-cannon requested changes
we still want to keep the gradle plugin, and the Java code for helm tools.  at least until we do a redesign on FST based on updates with solo-operator/etc.

2024-10-09 14:09 UTC, JeffreyDallas commented on fullstack-core/fullstack-helm-client/build.gradle.kts
But if we remove charts directory, many of helm related java code would not compile or test would fail.
maybe we just keep charts and docker directory untouched then ?

2024-10-09 17:16 UTC, jeromy-cannon commented on fullstack-core/fullstack-helm-client/build.gradle.kts
I'll need to take a look and see what you are talking about.  It might just be a matter of updating the examples or test cases to not use FST helm charts, or switch them to the Solo Helm charts.

2024-10-10 02:01 UTC, JeffreyDallas commented
Created two new separate PRs

2024-10-10 02:01 UTC, closed without merging